### ISSUE TITLE
Userspace proxy?

### ISSUE THREAD

**Issue by bboreham** [hobby-kube/guide#11]
Hi, I work on Weave Net, and I wonder if you could give a few pointers how you came to this conclusion:

> To cut a long story short kube-proxy needs to be patched to run in userspace mode.

I must have built a thousand Kubernetes clusters, and don't recall ever switching `kube-proxy` into userspace mode.

**Comment by pstadler** [comment]
Related issue: https://github.com/kubernetes/kubeadm/issues/66

Even though this issue was closed, the fix still needs to be applied with Kubernetes v1.6.2.

Please let me know if there's a better way to handle this.

**Comment by bboreham** [comment]
Thanks; I find it difficult to tell from that issue what exactly went wrong, but please take a look at https://github.com/kubernetes/kubeadm/issues/102#issuecomment-291532883 and see if this matches your situation.

**Comment by jackielii** [comment]
I just deployed a cluster very similar to what this guide described:

1. apt install ...
2. kubeadm init
3. deploy weave-net

all worked without a problem

**Comment by pstadler** [comment]
Did you deploy multiple nodes?

**Comment by jackielii** [comment]
Yes, I have one master, 4 nodes. It's all on the scrapped machines the office have. My boss was delighted that the old machines can actually be put to use.

Interestingly I had master on a vm, and the nodes on bare metal. All installed with Ubuntu 1604LTS though.

**Comment by pstadler** [comment]
Thanks for your response. Will further investigate this in the coming days.

**Comment by xeor** [comment]
Did you figure anything out?

Guess this issue will only show up if you are using `wireguard` (ie, another interface)..

**Comment by pstadler** [comment]
Not yet, I'm currently fighting deadlines at work. Please let me know if you make progress in this regard.

**Comment by pstadler** [comment]
Finally fixed this with https://github.com/hobby-kube/guide/commit/6b52d1b26058e39ea2e755bbaa0015af2d5fa04c

Thanks for the hint, works like a charm.
