### ISSUE TITLE
Starting etcd.service hangs attempting to contact peers

### ISSUE THREAD

**Issue by programatt** [hobby-kube/guide#12]
I'm at the step where the etcd cluster is brought up by starting the etcd.service on each host. I've validated that the VPN connections are ok using wg show. 
`
root@kube1:~# wg show
interface: wg0
  public key: qSQ/xnfVbSYIjo77TZeswUVV2nB4V9gO6Q0uVIEgdCY=
  private key: (hidden)
  listening port: 51820

peer: AcTw0SN6h9fqfIB25zIqpEEob7Qjum+r29qOHFzrdUY=
  endpoint: 10.8.23.94:51820
  allowed ips: 10.0.1.2/32
  transfer: 0 B received, 21.54 KiB sent

peer: dCu52IH4TgIxbk+MP11PwO8oIzrv9dH4K/ZjIOy9mmo=
  endpoint: 10.8.23.95:51820
  allowed ips: 10.0.1.3/32
  transfer: 0 B received, 21.39 KiB sent
`

The `systemctl start etcd.service` call never returns. Looking at `journalctl -u etcd.service` shows the following lines over and over till i killed the start call.

`May 09 20:16:06 kube1 etcd[32490]: health check for peer 910054c0ee2bca8d could not connect: dial tcp 10.0.1.3:2380: i/o timeout
May 09 20:16:06 kube1 etcd[32490]: health check for peer 940feae903dd7834 could not connect: dial tcp 10.0.1.2:2380: i/o timeout
`
For context I'm attempting this using virtualbox on OSX with ubuntu 16.04 server and bridged network card settings.

**Comment by programatt** [comment]
It appears that even though wg show looks similar to what you have in the guide, I'm unable to ping the other hosts over the VPN IP Address. So i think this issue is with the VPN setup

**Comment by programatt** [comment]
I'm just going to close this issue, the more digging into it I do the more this appears to be an issue with trying to use virtualbox bridge adapter networking than this guide.

**Comment by pstadler** [comment]
If you really want to use it in this scenario, make sure to bind it to the correct IP address as it seems like you simply used the example values (10.8.23.93-95).

**Comment by programatt** [comment]
Ah, that's the part i was missing. I'm not super versed with networking on linux so it was a bit above me to try and follow that part once I started having issues. That makes way more sense! Thanks
