### ISSUE TITLE
kubectl connection

### ISSUE THREAD

**Issue by orrakprime** [hobby-kube/guide#13]
I'm trying to do this guide by simulating a cloud environment locally.  I have 3 Virtualbox Ubuntu servers and following the guide to create a 3 node cluster.  Everything was working fine until I got to the Weave Net configuration.  When I invoke kubectl to install Weave Net I get:
 root@kube1:/etc/kubernetes# kubectl apply -f https://git.io/weave-kube-1.6
The connection to the server kube1:8080 was refused - did you specify the right host or port?

any suggestions to what may be wrong?
Thanks.

**Comment by pstadler** [comment]
Make sure to create a symlink to the kubectl configuration that kubeadm wrote to `/etc/kubernetes/admin.conf` during initialization:

`ln -s /etc/kubernetes/admin.conf $HOME/.kube/config`

References:
- https://github.com/hobby-kube/guide#kubernetes-setup
- https://github.com/hobby-kube/provisioning/blob/7cd81dc205e0a6192137b73624cb09dd1e61f151/service/kubernetes/scripts/master.sh#L8
