### ISSUE TITLE
WireGuard already ships systemd unit for wg-quick

### ISSUE THREAD

**Issue by zx2c4** [hobby-kube/guide#15]
Hey,

Great guide. Thanks for writing it and for the inclusion of WireGuard. Nice to see.

I noticed that you're providing instructions on creating a custom unit for systemd. Actually, WireGuard already ships with the `wg-quick@.service` unit, which is ± exactly what you have in here. Thus, rather than instructing users to create a new unit, you may simple instruct them to `systemctl enable wg-quick@wg0` and `systemctl start wg-quick@wg0`. The Ubuntu packages should be installing this automatically, and if you're compiling and installing manually, `make install` will automatically install this unit file too.

Jason

**Comment by pstadler** [comment]
Kind of missed that. Thank you.

**Comment by pstadler** [comment]
Also changed and verified here: https://github.com/hobby-kube/provisioning/commit/af47a8fbdaeeeb78ac2fe77ed55a0dab489a2185
