### ISSUE TITLE
had some trouble with newer versions of terraform

### ISSUE THREAD

**Issue by quidome** [hobby-kube/guide#16]
Once I found the proper version (0.9.6, not higher) I finally got it to build the entire cluster.

I continued and used all the manifests too. Everything seems to be covered, I now have a very nice running k8s cluster. Great guide!

**Comment by pstadler** [comment]
Thanks. Unfortunately this is not the first time I see Terraform plans failing after an update. Will try to figure out what's wrong.

**Comment by pstadler** [comment]
I just provisioned a new cluster using Terraform 0.9.11, no problems at all.
