### ISSUE TITLE
HA on Distributed Block Storage

### ISSUE THREAD

**Issue by prat0318** [hobby-kube/guide#17]
As per [Distributed Block storage section, ](https://github.com/hobby-kube/guide#distributed-block-storage) I understand that the devices on the nodes will be used to create PVs and if a pod goes down, it will again attach to the previous PV it was attached to. One thing i am quite not sure about is if a node goes down (along with its attached device), will its PV be still visible/available because the `repl` count is set to 2? Which means solutions like `portworx`can separate out PVs from devices and PVCs will still continue to work even if a single disk fails?

**Comment by pstadler** [comment]
That's at least the idea. I never tried this though. You may want to refer to the official documentation.

- [Portworx Documentation](https://docs.portworx.com/)
- [px-dev on GitHub](https://github.com/portworx/px-dev)
