### ISSUE TITLE
Question on opening ports in ufw

### ISSUE THREAD

**Issue by WishCow** [hobby-kube/guide#2]
Hey,

Thanks a lot for this guide, I managed to setup my own cluster in a few hours, it's really informative.

There is one thing I'm wondering about, in the firewall section, what is the purpose of opening port 443, and 80 on all the nodes? Since later on you constrain the ingress controller to always run on node1, wouldn't it be enough to open the ports on that node only, since it's only the ingress controller that needs to accept external traffic on those ports?

**Comment by pstadler** [comment]
Yes, that's correct. I didn't mention this for the sake of simplicity.
