### ISSUE TITLE
upgrading hobby kube cluster

### ISSUE THREAD

**Issue by maleck13** [hobby-kube/guide#21]
Hey, Wondering what the options are for upgrading a hobby kube cluster? Any thoughts on this, is there a way to set the version of kubernetes? If this was an option then tearing it down and back up would be an option.

**Comment by pstadler** [comment]
There's an upgrade guide located here: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm-upgrade-1-7/

I usually deploy a new cluster and migrate my data manually, because doing it this way, I can assure that this guide is still correct and provisioning works.

**Comment by pstadler** [comment]
Feel free to add further comments or questions here.
