### ISSUE TITLE
Need to allow port for weave ?

### ISSUE THREAD

**Issue by nkzawa** [hobby-kube/guide#27]
I had a problem that `kube-dns` never change the status from `ContainerCreating` to `Running`, and it was because weave couldn't establish connections like the following:

```
$ weave status connections
-> 10.8.57.9:6783        failed      cannot connect to ourself, retry: never
-> 10.8.166.137:6783     retrying    dial tcp4 :0->10.8.166.137:6783: getsockopt: connection timed out
-> 10.8.55.201:6783      retrying    dial tcp4 :0->10.8.55.201:6783: getsockopt: connection timed out
```

And it was fixed when I allowed the port `6783` on firewall on all nodes like:

```
ufw allow 6783
ufw reload
```

Is it actually required to add to the guide, or I wonder if I was missing some configurations.

**Comment by pstadler** [comment]
Try adding the following routes instead:

```
ip route add 10.96.0.0/16 dev $VPN_INTERFACE src $VPN_IP

# on kube1:
ip route add 10.96.0.0/16 dev wg0 src 10.0.1.1
# on kube2:
ip route add 10.96.0.0/16 dev wg0 src 10.0.1.2
# on kube3:
ip route add 10.96.0.0/16 dev wg0 src 10.0.1.3
```

**Comment by nkzawa** [comment]
Actually, I had added `ip route add 10.96.0.0/16 dev wg0 src 10.0.1.?` as well to each node, but somehow it didn't work for me.

I deleted the firewall setting and tested it again, but didn't work 🤔

**Comment by pstadler** [comment]
How did you deploy weave?

Are your weave pods restarting frequently due to errors? `kubectl get pods -n kube-system -l name=weave-net -o wide`

**Comment by nkzawa** [comment]
I deployed it like
```
# install Weave Net
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```

Currently pods look like the following since once I deleted these pods to test.
```
$ kubectl get pods -n kube-system -l name=weave-net -o wide
NAME              READY     STATUS    RESTARTS   AGE       IP             NODE
weave-net-7gktz   2/2       Running   0          28m       10.8.57.9      exprs-cluster-1
weave-net-7jgt9   2/2       Running   0          28m       10.8.166.137   exprs-cluster-2
weave-net-vvr45   2/2       Running   0          28m       10.8.55.201    exprs-cluster-3
```

It seems `weave-net` doesn't restart frequently even if weave connection is not established. Only `kube-dns` was affected.

**Comment by pstadler** [comment]
Your pods are bound to the wrong IP subnet (should be 10.0.1.1-3). Maybe there's a problem with your master node listening on the wrong port.

**Comment by nkzawa** [comment]
@pstadler hmm, thanks for taking your time.  Unfortunately I have no idea how to fix it :( I appreciate if you could point out documents about it.

**Comment by pstadler** [comment]
1. Make sure you correctly set up your wireguard VPN
2. Make sure services (etcd, kubernetes) are bound to the VPN interface (wg0) using the VPN IP addresses (10.0.1.1-3).

The guide should contain sufficient information. Another option is to try https://github.com/hobby-kube/provisioning if you can't solve this problem.

**Comment by nkzawa** [comment]
@pstadler I set up servers from scratch, then the firewall setting is not required anymore. I still don't know why it happened tho. Thank you again for your help and this awesome guide.

**Comment by pstadler** [comment]
Glad to hear that 👍

**Comment by nkzawa** [comment]
@pstadler sorry again, the weave issue was fixed, but somehow my kubernetes nodes are not bound to the VPN interface (wg0) when I manually setup. (When I use https://github.com/hobby-kube/provisioning, it works fine). I appreciate if you could point out where/how it's configured. I checked the terraform configurations but couldn't find differences :(
