### ISSUE TITLE
Question: why not run etcd in docker ?

### ISSUE THREAD

**Issue by jpic** [hobby-kube/guide#29]
Maybe this is a stupid question but i'm wondering if it wouldn't be easier to just create an etcd container which restarts on each node, rather than using another systemd service.

Did you consider this option ?
What are your thoughts about it ?
Thanks ! Great guide btw ;)

**Comment by pstadler** [comment]
I'm not sure if this is even possible, e.g. during startup this might turns into a _chicken or the egg_ problem. Wouldn't recommend this, but I get the idea. Please let me know your findings 👍
