### ISSUE TITLE
Update DigitalOcean Pricing

### ISSUE THREAD

**Issue by adamelliotfields** [hobby-kube/guide#30]
DigitalOcean has updated their pricing for 2018: https://blog.digitalocean.com/new-droplet-plans/

1 vCPU/1GB VMs are now only $5, so running a 3-node cluster is only $15/mo instead of $30/mo.

DigitalOcean has also enhanced their security for private networks: https://www.digitalocean.com/community/tutorials/digitalocean-private-networking-faq

**I can gladly submit a PR with an updated `README.md` to reflect the pricing changes.**

Disclaimer: Not affiliated with DO in any way (until now I've been using Vultr).

**Comment by pstadler** [comment]
Good news. A PR would be welcome. Kind of related: https://github.com/hobby-kube/guide/issues/28

**Comment by adamelliotfields** [comment]
Do you want me to replace Scaleway with Hetzner as "the very best offer"? Or do you want to try the Terraform recipe first?

**Comment by pstadler** [comment]
I'd be glad if you could just handle the DigitalOcean related changes.

My cluster is currently running on Hetzner Cloud, looking good, but the provisioning part is not ready yet.
