### ISSUE TITLE
Scaleway doesn't allow you to add more SSDs

### ISSUE THREAD

**Issue by norbert-yoimo** [hobby-kube/guide#4]
I was about to set up persistent volumes for my cluster, but it looks like scaleway doesn't allow you to add more than 50GB storage to a single instance. If you try to start your instance with more than 50GB storage attached, you will get an error:

```
The total volume size of VC1S instances must be equal or below 50GB
```

I think it's worth mentioning in the README that PVs are not a possibility on scaleway (haven't tried digital ocean yet).

**Comment by pstadler** [comment]
Please see this issue: https://github.com/scaleway/image-tools/issues/184

You can in fact attach further disks (more than 50GB in total), but it's
currently almost impossible to automate it using Terraform. I ended up
creating a 30GB Ubuntu image which can be used to attach another 20GB disk.
Unfortunately, images cannot be shared publicly and the process to create
one is just awful. Please consider adding a comment to the issue mentioned
above.

**Comment by norbert-yoimo** [comment]
Right, attaching the disks is fine, however, you cannot **start** the instance, if you have more than 50 GB attached, which is probably what terraform is also running into, see:

https://community.online.net/t/arm64-2gb-volume-limitation/4492

**Comment by pstadler** [comment]
That's unfortunate, I didn't know such restrictions exist. This leaves us with the following options for now:

- Create a smaller custom image to stay below the total limit. Impractical, but works
- Create a virtual block device ([example](https://superuser.com/questions/686064/how-to-attach-a-virtual-hard-drive-to-occupy-dev-sdb))
- Use the more expensive VC1M (2x50GB or more)

**Comment by pstadler** [comment]
Related: https://community.online.net/t/wrongful-volume-billing/4539

**Comment by pstadler** [comment]
I will close this issue. Scaleway has been a pain to work with and support is basically nonexistent. I'm planning to give the crown to Hetzner Cloud soon. See #28
