### ISSUE TITLE
Add note on integrating with external DNS provider

### ISSUE THREAD

**Issue by johanbrandhorst** [hobby-kube/guide#40]
Hi!

Just found this project, fantastic work! I'm interested in trying it out, but I already have a DNS provider, and I was a little confused as to exactly how I would integrate my existing provider with this setup. Could you add a little note explaining what records to set? I see the example records, but the addition of the terraform files for google/aws/cloudflare makes me wonder if there's anything more I need to add.

Thanks!

**Comment by pstadler** [comment]
- `A` record with your **TLD** pointing to the IP of kube1 (or wherever your ingress is located)
- `CNAME` wildcard (`*`) alias of **TLD** for subdomains
