### ISSUE TITLE
Add guide to non-vendorcloud (i.e. on prem Bare Metal) installs

### ISSUE THREAD

**Issue by seffyroff** [hobby-kube/guide#41]
As a hobbyist, I don't want my projects to unnecessarily burn cash by consuming cost-per-resource-over-time whilst iterating over configurations.  Using locally available commodity hardware which I and most hobbyists I know generally have available is a more efficient way to host projects such as this.

I appreciate this is a challenge with Terraform not having a provider for bare metal without being opinionated (the Digital Rebar or Matchbox providers seem the best option) but perhaps the most agnostic way to accomplish this would be via the Salt-Masterless provisioner?  Another approach that might simplify the process somewhat whilst introducing a thin layer of abstraction could be to use LXC/D, perhaps in conjunction with Packer images?

**Comment by pstadler** [comment]
It would make a lot of sense to simply launch some containers using the Terraform Docker provider[1] to simply try things out. I'm reluctant to introduce complex commodity hardware provisioning. Let me know what you think.

[1] https://www.terraform.io/docs/providers/docker/r/container.html
