### ISSUE TITLE
Have you considered network namespaces?

### ISSUE THREAD

**Issue by ieugen** [hobby-kube/guide#44]
Hello, 

While researching wireguard and docker I came across the documentation page about wireguard routing and linux network namespaces. I think it can improve security since all docker containers can only access other hosts inside wireguard. This is also true for other applications started inside the namespace. 

https://www.wireguard.com/netns/
https://medium.com/@ApsOps/an-illustrated-guide-to-kubernetes-networking-part-1-d1ede3322727
https://blog.scottlowe.org/2013/09/04/introducing-linux-network-namespaces/
https://medium.com/google-cloud/understanding-kubernetes-networking-pods-7117dd28727

**Comment by ieugen** [comment]
It seems that kubernetes already uses network namespaces but they are not visible using ip netns.

**Comment by pstadler** [comment]
This issue went under my radar. I think it doesn't make much sense to use this feature.
