### ISSUE TITLE
Is it possible to have multiple ingress controllers?

### ISSUE THREAD

**Issue by jokogr** [hobby-kube/guide#61]
Is it possible to have multiple ingress controllers, one per node?

I was thinking about designing a multi-cloud cluster with one node per different cloud provider and using global server load balancing.

**Comment by pstadler** [comment]
This should be possible using a `NodePort` service type. See this manifesto for example: https://github.com/kubernetes/ingress-nginx/blob/master/deploy/provider/baremetal/service-nodeport.yaml

For what it's worth, the current situation using `hostPort` to bind to low ports is probably outdated and should be changed to leverage the `NodePort` service type.

**Comment by pstadler** [comment]
So it turned out that `NodePort` does not work in our case. I suggest that you change your ingress controller from `Deployment` to `DaemonSet`. In this case you would have an ingress controller running on each host.
