### ISSUE TITLE
Consider a section for non-HTTP services

### ISSUE THREAD

**Issue by outime** [hobby-kube/guide#67]
First of all, this is the best guide I've ever read about setting up a decent K8s setup with enough level of details but not too much that it'd overwhelm newcomers or people with superficial knowledge. Thank you for doing this!

The guide mostly covers web services very well but not other type of services (say SFTP). Do you think it would be interesting enough to cover such use case on this guide?

**Comment by pstadler** [comment]
You would simply need to open another port and bind nginx to it; or you expose non-HTTP services on either 80 or 443. Keep in mind that in case of SFTP, port 22 cannot be used unless you bind SSH to another port or a different network interface.

Related: https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

I don't think that this requires an extra section in the guide at this point.
