### ISSUE TITLE
Have you looked at the CIS Security Guide for Kubernetes yet?

### ISSUE THREAD

**Issue by praving55** [hobby-kube/guide#7]
Have you looked at the CIS Security Guide for Kubernetes yet? If not, it is getting released next week. It is in the preview as of now. You may signup for this. There are quite a few security configuration items that might help you to improve the guide.
To sign up check - [https://cavirin.com/kubernetes.html](https://cavirin.com/kubernetes.html)

**Comment by pstadler** [comment]
Interesting, will keep an eye on it. Looks more like something targeted at the enterprise market to be honest.
