### ISSUE TITLE
Terraform borks up on `count` keyword

### ISSUE THREAD

**Issue by lbialy** [hobby-kube/guide#76]
I get this with terraform `0.12.3`:

```
Error: Reserved argument name in module block

  on main.tf line 48, in module "swap":
  48:   count       = "${var.node_count}"

The name "count" is reserved for use in a future version of Terraform.
```

Apparently some renaming is now a must.

**Comment by lbialy** [comment]
Replacing `count` with `node_count` everywhere and `version` with `etcd_version` everywhere solves this.

**Comment by masterkain** [comment]
I'm having issues with 0.12 as well, did you manage to get it working?

**Comment by lbialy** [comment]
Yeah, just replace count variable with node_count and version variable with etcd_version everywhere.

**Comment by masterkain** [comment]
yes, did that in order to prepare a pr, but I met a lot of other errors,
I'm away from computer but some were about unallowed var blocks. tried with
latest tf version?

**Comment by lbialy** [comment]
Hmm, not yet.

**Comment by pstadler** [comment]
Currently very busy here. Terraform 0.12 seems to break a lot of code. Will try to catch up as soon as possible. You should stick with 0.11 until then.

**Comment by pstadler** [comment]
This will be fixed with https://github.com/hobby-kube/provisioning/pull/48

**Comment by pstadler** [comment]
This has been fixed with https://github.com/hobby-kube/provisioning/pull/48
