### ISSUE TITLE
Add IBM provider maybe?

### ISSUE THREAD

**Issue by lbialy** [hobby-kube/guide#77]
IBM has opened their cloud for partners ([link](https://www.ibm.com/partners/build/)) and it looks like a year of operation for free with a lot of additional toys accessible. There's a IBM cloud terraform provider, but I didn't have time to check whether it would be up to hobby-kube's requirements.

**Comment by pierreozoux** [comment]
I don't think that IBM qualifies as a cloud for hobbyist ;)

**Comment by pstadler** [comment]
I would certainly consider adding an IBM Cloud provider to hobby-kube/provisioning if somebody opens a quality PR over there.

Pricing for virtual servers can be found here: https://www.ibm.com/cloud/virtual-servers/pricing/
