### ISSUE TITLE
AWS spot instances might be affordable for a hobby cluster

### ISSUE THREAD

**Issue by JWDobken** [hobby-kube/guide#82]
The Readme states that a three node cluster on Hetzner Cloud cost a little less than €7.50/month for 3x2GB nodes (1vCPU). But with an hour price of €0.005 this would actually cost 3x €3.65 = €10.95 per month

If you take a slightly better [AWS spot instance](https://aws.amazon.com/ec2/spot/pricing/), let's say the t3.small:

- t3.small with 2 vCPU and 2.0 GB, 3x $5.256 = $15.768 -> €14.37 per month

I would say, with all the benefits of AWS like S3 storage and auto-scaling, definitely something to consider.

**Comment by pstadler** [comment]
While I agree with what you're saying, I just wanted to note that a Hetzner node still runs for €2.49 per month. Typically, I'm attaching 10GB extra storage (€0.40) to each node. My last 3 bills were always €9.34 (incl. VAT).

**Comment by pstadler** [comment]
I would certainly consider adding an AWS provider to hobby-kube/provisioning if somebody opens a quality PR over there.
