### ISSUE TITLE
"example-ingress" is invalid

### ISSUE THREAD

**Issue by nfalcone** [hobby-kube/guide#85]
Getting this message in the guide when applying ingress controller.

`The Ingress "example-ingress" is invalid: spec.rules[0].http.paths[0].backend.servicePort: Invalid value: "example-service-http": must be no more than 15 characters`

Solution: changed name from example-ingress to test-ingress

**Comment by pstadler** [comment]
I finally got time to update this. Thanks for your report. At some point I'm going to update all manifests to use recent API versions.
