### ISSUE TITLE
Scaleway is changing their pricing plan

### ISSUE THREAD

**Issue by 4ndrewHarri5** [hobby-kube/guide#86]
It will be more expensive to deploy this guide using scaleway as they are changing their pricing plan in August. It's jumped up from 2.99 Euros to 4.99 Euros per month. Not a massive change for one instance but means spending just under 15 euros instead of 9 euros a month for this set up.

You can see the changes [here](https://blog.scaleway.com/2020/price-evolutions-cloud-instances/).

So just a warning incase anyone is thinking about using scaleway or is already using them to be aware of these changes 👍

**Comment by pstadler** [comment]
That's actually a 66% price increase. Thanks for mentioning.

**Comment by pstadler** [comment]
Updated: https://github.com/hobby-kube/guide/commit/bfdf05f089b552f82bf4dab0bc454cbbf4bd617b
