### ISSUE TITLE
Include OVH?

### ISSUE THREAD

**Issue by 94b1** [hobby-kube/guide#9]
OVH is one of the best vale/price VPS providers. Their cheapest offering - [VPS SSD 1](https://www.ovh.com/us/vps/vps-ssd.xml) is $3.49 for 1 core and 2 GB RAM. It has a data center in Beauharnois, Canada which should provide much better latency than Scaleway.

**Comment by pstadler** [comment]
Please open a pull request here: https://github.com/hobby-kube/provisioning
